


import json
import io
import traceback

# Your complete response.text string, including the final chunk
response_text = """216
[["wrb.fr",null,"[null,[null,\"r_5903e860041f4864\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"r_5903e860041f4864\",null,null,[\"Oct6I77K4uVAxHDtRoAGZieS5aAreEs6mPs0Niw0s1I\"]]"]]
1048
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\":\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\":\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1056
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.6\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.6\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1096
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\":\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\":\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1122
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1152
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1222
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1284
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1360
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1446
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1556
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1632
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and analyst ratings show a 'hold' or 'buy\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and analyst ratings show a 'hold' or 'buy\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1724
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and analyst ratings show a 'hold' or 'buy' consensus with an average target price above\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and analyst ratings show a 'hold' or 'buy' consensus with an average target price above\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1816
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and analyst ratings show a 'hold' or 'buy' consensus with an average target price above the current market price, suggesting a likely\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and analyst ratings show a 'hold' or 'buy' consensus with an average target price above the current market price, suggesting a likely\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1866
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and analyst ratings show a 'hold' or 'buy' consensus with an average target price above the current market price, suggesting a likely upward movement.\\\"\\n}\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and analyst ratings show a 'hold' or 'buy' consensus with an average target price above the current market price, suggesting a likely upward movement.\\\"\\n}\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1946
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and analyst ratings show a 'hold' or 'buy' consensus with an average target price above the current market price, suggesting a likely upward movement.\\\"\\n}\"],[],null,null,null,true,null,[2],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,true,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and analyst ratings show a 'hold' or 'buy' consensus with an average target price above the current market price, suggesting a likely upward movement.\\\"\\n}\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]],null,null,null,null,null,null,null,null,null,null,null,null,\"9ec249fc9ad08861\"]"]]
227
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"AwAAAAAAAAAQwBHO-LzoF6KdIMPalhk\"]"]]
59
[["di",3802],["af.httprm",3802,"2858374046706730903",60]]
28
[["e",20,null,null,21932]]
"""

import json
import re

def parse_google_ai_response(response_text):
    """
    Parses a streaming response from the Google AI API to extract and reconstruct
    the final JSON output.

    Args:
        response_text (str): The raw text of the API's streaming response.

    Returns:
        dict: The final, parsed JSON object as a Python dictionary.
    
    Raises:
        ValueError: If the response cannot be parsed or the final JSON is invalid.
    """
    full_json_string = ""
    lines = response_text.strip().split('\n')

    for line in lines:
        line = line.strip()
        if not line:
            continue

        # The lines are formatted with a length header followed by the content.
        # We need to find the start of the JSON array.
        json_match = re.search(r'\[\[.*', line)
        if json_match:
            try:
                # The data is a stringified JSON array. We need to parse it.
                raw_json_chunk = json_match.group(0)
                parsed_data = json.loads(raw_json_chunk)
                
                # Check for the specific nested structure where the output is located.
                # This is based on empirical observation of the API's response format.
                if len(parsed_data) > 0 and isinstance(parsed_data[0], list):
                    # Check for a specific key that often precedes the JSON data.
                    # This helps filter out non-essential parts of the response.
                    if len(parsed_data[0]) > 2 and isinstance(parsed_data[0][2], str):
                        inner_data = json.loads(parsed_data[0][2])
                        
                        # Navigate to the specific path where the string fragments are stored.
                        # The path [4][0][1] is a common pattern for the main response payload.
                        if len(inner_data) > 4 and isinstance(inner_data[4], list):
                            if inner_data[4] and isinstance(inner_data[4][0], list):
                                if len(inner_data[4][0]) > 1 and isinstance(inner_data[4][0][1], list):
                                    string_fragments = inner_data[4][0][1]
                                    full_json_string += "".join(string_fragments)

            except (json.JSONDecodeError, IndexError) as e:
                # Silently ignore chunks that don't conform to the expected structure
                # as they are often metadata or control signals.
                continue

    # After iterating through all lines, parse the concatenated string
    if full_json_string:
        try:
            # The final JSON string needs to be properly un-escaped and parsed.
            final_output = json.loads(full_json_string)
            return final_output
        except json.JSONDecodeError:
            raise ValueError("Failed to parse the final JSON object.")
    else:
        raise ValueError("No parsable JSON content found in the response.")


# Example usage with your provided response text
response_text = """
216
[["wrb.fr",null,"[null,[null,\"r_5903e860041f4864\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"r_5903e860041f4864\",null,null,[\"Oct6I77K4uVAxHDtRoAGZieS5aAreEs6mPs0Niw0s1I\"]]"]]
1048
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\":\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\":\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1056
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.6\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.6\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1096
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\":\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\":\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1122
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1152
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1222
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1284
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1360
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1446
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1556
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1632
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and analyst ratings show a 'hold' or 'buy\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and analyst ratings show a 'hold' or 'buy\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1724
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and analyst ratings show a 'hold' or 'buy' consensus with an average target price above\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and analyst ratings show a 'hold' or 'buy' consensus with an average target price above\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1816
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and analyst ratings show a 'hold' or 'buy' consensus with an average target price above the current market price, suggesting a likely\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and analyst ratings show a 'hold' or 'buy' consensus with an average target price above the current market price, suggesting a likely\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1866
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and analyst ratings show a 'hold' or 'buy' consensus with an average target price above the current market price, suggesting a likely upward movement.\\\"\\n}\"],[],null,null,null,true,null,[1],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,false,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and analyst ratings show a 'hold' or 'buy' consensus with an average target price above the current market price, suggesting a likely upward movement.\\\"\\n}\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]]]"]]
1946
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,[[\"rc_32cfc47281d8e744\",[\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and analyst ratings show a 'hold' or 'buy' consensus with an average target price above the current market price, suggesting a likely upward movement.\\\"\\n}\"],[],null,null,null,true,null,[2],\"en\",null,null,[null,null,null,null,null,null,[0],[]],null,null,true,null,null,null,null,null,[false],null,false,[],true,null,null,[]]],[\"Siddhivinayak Nagar, Amravati, Maharashtra, India\",\"SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS\",false,null,\"//www.google.com/maps/vt/data\\u003deXNQVukl61rgpLlE-dlnID0zI8Mj4Vy1yXIduqH5OAgYh7iiGYxq8Pnz3GoExWwVDnWWS_VL2G2-q1jYnIWuhmvn6C2u2CfwdCA7zgfU7CYqfmfljy5bnHXonIy6lt8FE5a5Wzrqg40456Xln4mQhfaq3ipP_elXnBXypYSmN_fGW-kVl9CQzVBlolgWag\"],null,null,\"IN\",null,null,[[null,[\"google_search\",[\"\",null,\"Google Search\",\"https://www.gstatic.com/images/branding/productlogos/googleg/v6/192px.svg\",\"search\"],4]]],null,null,true,null,null,null,null,\"en\",null,null,null,true,[null,[false,false]],null,[[[[null,[null,0,\"{\\n\\\"P_up\\\": 0.65,\\n\\\"P_down\\\": 0.25,\\n\\\"P_side\\\": 0.1,\\n\\\"trend\\\": \\\"uptrend\\\",\\n\\\"reasoning\\\": \\\"Bajaj Auto is in a rising trend channel and has a positive signal from an inverse head and shoulders formation. Most technical indicators and analyst ratings show a 'hold' or 'buy' consensus with an average target price above the current market price, suggesting a likely upward movement.\\\"\\n}\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"0\"]]]],null,null,null,null,null,null,null,null,null,null,null,null,\"9ec249fc9ad08861\"]"]]
227
[["wrb.fr",null,"[null,[\"c_dbe858dd92148c66\",\"r_5903e860041f4864\"],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"AwAAAAAAAAAQwBHO-LzoF6KdIMPalhk\"]"]]
59
[["di",3802],["af.httprm",3802,"2858374046706730903",60]]
28
[["e",20,null,null,21932]]
"""
try:
    parsed_json = parse_google_ai_response(response_text)
    print(json.dumps(parsed_json, indent=2))
except ValueError as e:
    print(f"Error: {e}")